drop table if exists address;
drop table if exists address_country;
drop table if exists address_city;
drop table if exists address_state;
drop table if exists brand;
drop table if exists brand_address;
drop table if exists campaign;
drop table if exists campaign_participating_products;
drop table if exists campaign_valid_locations;
drop table if exists product;
create table address (id integer not null auto_increment, address_type integer, complement varchar(255), postal_code varchar(255), street_name varchar(255), street_number integer not null, city_id integer not null, primary key (id)) engine=InnoDB;
create table address_country (id integer not null auto_increment, code varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table address_city (id integer not null auto_increment, name varchar(255), state_id integer, primary key (id)) engine=InnoDB;
create table address_state (id integer not null auto_increment, code varchar(255), name varchar(255), country_id integer, primary key (id)) engine=InnoDB;
create table brand (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table brand_address (brand_id integer not null, address_id integer not null) engine=InnoDB;
create table campaign (id integer not null auto_increment, campaign_type integer, name varchar(255), purchase_from datetime(6), purchase_until datetime(6), valid_from datetime(6), valid_until datetime(6), promoter_id integer, primary key (id)) engine=InnoDB;
create table campaign_participating_products (campaign_id integer not null, participating_products_id integer not null) engine=InnoDB;
create table campaign_valid_locations (campaign_id integer not null, valid_locations_id integer not null) engine=InnoDB;
create table product (id integer not null auto_increment, class_of_good integer, ean varchar(255), name varchar(255), manufacturer_id integer, primary key (id)) engine=InnoDB;
alter table address_country add constraint UK_m2d5r5k0sby9o722yuafv7omp unique (code);
alter table brand_address add constraint UK_bu3w4hh38xpervyyxihjvatfg unique (address_id);
alter table campaign_valid_locations add constraint UK_4t70qra18ky427n3mp2t9hd9p unique (valid_locations_id);
alter table address add constraint FKrik8v4to727difjd01h536yoh foreign key (city_id) references address_city (id);
alter table address_city add constraint FKolhfhc6dpr7uj2q1i6esh8abq foreign key (state_id) references address_state (id);
alter table address_state add constraint FKgqwuk0ub92gqaao8yy55randy foreign key (country_id) references address_country (id);
alter table brand_address add constraint FKl3tknkblcytngl2miswct2mob foreign key (address_id) references address (id);
alter table brand_address add constraint FKok7evdg0ggf0q6k3ctgtwp3s5 foreign key (brand_id) references brand (id);
alter table campaign add constraint FK8g63dd85obdrplh65lt9cgiby foreign key (promoter_id) references brand (id);
alter table campaign_participating_products add constraint FK8jyjq6hjxsyoudmwffewinomo foreign key (participating_products_id) references product (id);
alter table campaign_participating_products add constraint FKohh839i9eatmk8l8tl5ews7ia foreign key (campaign_id) references campaign (id);
alter table campaign_valid_locations add constraint FKcj38wej30te774mhse99qx9d3 foreign key (valid_locations_id) references address_country (id);
alter table campaign_valid_locations add constraint FKrocij1fji7lecn0sgh3tytcvp foreign key (campaign_id) references campaign (id);
alter table product add constraint FKry50i1b8xaii36petpx3lb696 foreign key (manufacturer_id) references brand (id);
